# Generated by Django 4.0 on 2021-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('audience_score', models.IntegerField(max_length=2)),
                ('critics_score', models.IntegerField(max_length=2)),
                ('movie_reviews', models.CharField(max_length=200)),
                ('youtube_trailer', models.CharField(max_length=200)),
            ],
        ),
    ]
