# Generated by Django 4.0 on 2021-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience_score',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='critics_score',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.SmallIntegerField(),
        ),
    ]
