# Generated by Django 4.0 on 2021-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieapp', '0002_alter_movie_audience_score_alter_movie_critics_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_url',
            field=models.CharField(max_length=200),
        ),
    ]
