# Generated by Django 4.0 on 2021-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieapp', '0003_alter_movie_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_reviews',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer',
            field=models.CharField(max_length=500),
        ),
    ]
