# Generated by Django 4.0 on 2021-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieapp', '0005_alter_movie_cast_alter_movie_movie_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience_score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='critics_score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(max_length=10),
        ),
    ]
