# Generated by Django 4.0 on 2021-12-12 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('themovieapp', '0006_alter_movie_audience_score_alter_movie_critics_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_reviews',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themovieapp.movie')),
            ],
        ),
    ]
